CREATE TABLE [dbo].[KorrektionsFact] (
    [Løbenr]       INT           IDENTITY (1, 1) NOT NULL,
    [BrugerGruppe] NVARCHAR (50) NULL,
    [Bruger]       NVARCHAR (50) NOT NULL,
	[Version] NVARCHAR(50) NOT NULL DEFAULT 'Ingen Version',
    [Dim01]        NVARCHAR (50) NOT NULL,
    [Dim01Value]   NVARCHAR (50) NOT NULL,
    [Dim02]        NVARCHAR (50) NOT NULL,
    [Dim02Value]   NVARCHAR (50) NOT NULL,
    [Dim03]        NVARCHAR (50) NOT NULL,
    [Dim03Value]   NVARCHAR (50) NOT NULL,
    [Dim04]        NVARCHAR (50) NOT NULL,
    [Dim04Value]   NVARCHAR (50) NOT NULL,
    [Dim05]        NVARCHAR (50) NOT NULL,
    [Dim05Value]   NVARCHAR (50) NOT NULL,
    [Dim06]        NVARCHAR (50) NOT NULL,
    [Dim06Value]   NVARCHAR (50) NOT NULL,
    [Dim07]        NVARCHAR (50) NOT NULL,
    [Dim07Value]   NVARCHAR (50) NOT NULL,
    [Dim08]        NVARCHAR (50) NOT NULL,
    [Dim08Value]   NVARCHAR (50) NOT NULL,
    [Dim09]        NVARCHAR (50) NOT NULL,
    [Dim09Value]   NVARCHAR (50) NOT NULL,
    [Dim10]        NVARCHAR (50) NOT NULL,
    [Dim10Value]   NVARCHAR (50) NOT NULL,
    [Belø]         FLOAT (53)    NOT NULL,
    [Kommentar]    TEXT          NOT NULL,
    [Dato] DATETIME NULL, 
    PRIMARY KEY CLUSTERED ([Løbenr] ASC)
);