'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=VBJXPS2017;Initial Catalog=Likviditetsmodul;Integrated Security=True")>  _
        Public ReadOnly Property LikviditetsmodulConnectionString() As String
            Get
                Return CType(Me("LikviditetsmodulConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Driver={Microsoft Excel Driver (*.xls)};dbq=C:\Users\vbj\Documents\Import_data_1."& _ 
            "xls;defaultdir=C:\Users\vbj\Documents;driverid=790;fil=excel 8.0;filedsn=C:\User"& _ 
            "s\vbj\source\repos\Finansial insight\Import excel.dsn;maxbuffersize=2048;maxscan"& _ 
            "rows=8;pagetimeout=5;readonly=1;safetransactions=0;threads=3;uid=admin;usercommi"& _ 
            "tsync=Yes")>  _
        Public ReadOnly Property ConnectionString() As String
            Get
                Return CType(Me("ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Driver={Microsoft Text-Treiber (*.txt; *.csv)};defaultdir=C:\Users\vbj\source\rep"& _ 
            "os\Finansial insight;driverid=27;fil=text;filedsn=C:\Users\vbj\source\repos\Fina"& _ 
            "nsial insight\Import csv.dsn;maxbuffersize=2048;maxscanrows=8;pagetimeout=5;safe"& _ 
            "transactions=0;threads=3;uid=admin;usercommitsync=Yes")>  _
        Public ReadOnly Property ConnectionString1() As String
            Get
                Return CType(Me("ConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Driver={Driver do Microsoft Excel(*.xls)};dbq=C:\Users\vbj\Documents\Import_data_"& _ 
            "1.xls;defaultdir=C:\Users\vbj\Documents;driverid=790;fil=excel 8.0;filedsn=C:\Us"& _ 
            "ers\vbj\source\repos\Finansial insight\Import excel.dsn;maxbuffersize=2048;maxsc"& _ 
            "anrows=8;pagetimeout=5;readonly=1;safetransactions=0;threads=3;uid=admin;usercom"& _ 
            "mitsync=Yes")>  _
        Public ReadOnly Property ConnectionString2() As String
            Get
                Return CType(Me("ConnectionString2"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Finansial_Insight_Excel_Import_Export.My.MySettings
            Get
                Return Global.Finansial_Insight_Excel_Import_Export.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
